# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from NumLib import DECIMAL_EXPR_REGEX, TERNAR_NUM_REGEX

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(656, 680)
        MainWindow.setStyleSheet("Qwidget {\n"
"    background-color: rgb(220, 138, 221);\n"
"}\n"
"QGroupBox {\n"
"    border:none;\n"
"}\n"
"QPushButton {\n"
"   background-color: rgb(255, 120, 0);\n"
"    border-width: 3px;\n"
"    border-style: solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"    height:80px;\n"
"    width:140px;\n"
"}\n"
"QPushButton:disabled {\n"
"background-color: rgb(119, 118, 123);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(230, 97, 0);\n"
"}\n"
"QRadioButton {\n"
"    border-width: 1px;\n"
"     border-style: solid;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-radius: 5px;\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(219, 74, 74);\n"
"    \n"
"    font: 75 35pt \"Uroob\";\n"
"}\n"
"QTabBar::tab {\n"
"    height:30px;\n"
"    font-size:9pt;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1001, 831))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridFrame = QtWidgets.QFrame(self.tab)
        self.gridFrame.setGeometry(QtCore.QRect(0, 90, 656, 514))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setStyleSheet("QPushButton {\n"
"    height:80px;\n"
"    width:140px;\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.digits_layout = QtWidgets.QGridLayout(self.gridFrame)
        self.digits_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.digits_layout.setObjectName("digits_layout")
        self.pushButton_eq = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eq.sizePolicy().hasHeightForWidth())
        self.pushButton_eq.setSizePolicy(sizePolicy)
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.digits_layout.addWidget(self.pushButton_eq, 4, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.digits_layout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.digits_layout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.digits_layout.addWidget(self.pushButton_clear, 4, 2, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plus.sizePolicy().hasHeightForWidth())
        self.pushButton_plus.setSizePolicy(sizePolicy)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.digits_layout.addWidget(self.pushButton_plus, 0, 3, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_minus.sizePolicy().hasHeightForWidth())
        self.pushButton_minus.setSizePolicy(sizePolicy)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.digits_layout.addWidget(self.pushButton_minus, 1, 3, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        self.pushButton_0.setObjectName("pushButton_0")
        self.digits_layout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.digits_layout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.digits_layout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_div.sizePolicy().hasHeightForWidth())
        self.pushButton_div.setSizePolicy(sizePolicy)
        self.pushButton_div.setObjectName("pushButton_div")
        self.digits_layout.addWidget(self.pushButton_div, 3, 3, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setAutoFillBackground(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.digits_layout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_tplus = QtWidgets.QPushButton(self.gridFrame)
        self.pushButton_tplus.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tplus.sizePolicy().hasHeightForWidth())
        self.pushButton_tplus.setSizePolicy(sizePolicy)
        self.pushButton_tplus.setObjectName("pushButton_tplus")
        self.digits_layout.addWidget(self.pushButton_tplus, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.digits_layout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.digits_layout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_erase = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_erase.sizePolicy().hasHeightForWidth())
        self.pushButton_erase.setSizePolicy(sizePolicy)
        self.pushButton_erase.setObjectName("pushButton_erase")
        self.digits_layout.addWidget(self.pushButton_erase, 4, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.digits_layout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_mult = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mult.sizePolicy().hasHeightForWidth())
        self.pushButton_mult.setSizePolicy(sizePolicy)
        self.pushButton_mult.setObjectName("pushButton_mult")
        self.digits_layout.addWidget(self.pushButton_mult, 2, 3, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dot.sizePolicy().hasHeightForWidth())
        self.pushButton_dot.setSizePolicy(sizePolicy)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.digits_layout.addWidget(self.pushButton_dot, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.digits_layout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_tminus = QtWidgets.QPushButton(self.gridFrame)
        self.pushButton_tminus.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tminus.sizePolicy().hasHeightForWidth())
        self.pushButton_tminus.setSizePolicy(sizePolicy)
        self.pushButton_tminus.setObjectName("pushButton_tminus")
        self.digits_layout.addWidget(self.pushButton_tminus, 3, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(30, 0, 601, 91))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lineEdit.setObjectName("lineEdit")


        self.decimal_validator = QtGui.QRegExpValidator(QtCore.QRegExp(DECIMAL_EXPR_REGEX))
        self.ternar_validator = QtGui.QRegExpValidator(QtCore.QRegExp(TERNAR_NUM_REGEX))
        self.lineEdit.setValidator(self.decimal_validator)

        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 600, 641, 57))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_decimal = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_decimal.setGeometry(QtCore.QRect(10, 10, 149, 37))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_decimal.sizePolicy().hasHeightForWidth())
        self.radioButton_decimal.setSizePolicy(sizePolicy)
        self.radioButton_decimal.setChecked(True)
        self.radioButton_decimal.setObjectName("radioButton_decimal")
        self.radioButton_thirth = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_thirth.setGeometry(QtCore.QRect(480, 10, 151, 37))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_thirth.sizePolicy().hasHeightForWidth())
        self.radioButton_thirth.setSizePolicy(sizePolicy)
        self.radioButton_thirth.setChecked(False)
        self.radioButton_thirth.setObjectName("radioButton_thirth")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 611, 631))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pushButton_eq.setText(_translate("MainWindow", "="))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_div.setText(_translate("MainWindow", "/"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_tplus.setText(_translate("MainWindow", "1"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_erase.setText(_translate("MainWindow", "<-"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_mult.setText(_translate("MainWindow", "*"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_tminus.setText(_translate("MainWindow", "i"))
        self.lineEdit.setText(_translate("MainWindow", "123+132"))
        self.radioButton_decimal.setText(_translate("MainWindow", "Decimal"))
        self.radioButton_thirth.setText(_translate("MainWindow", "Ternary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calc"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Программа создана студентом группы ИУ7-22Б Шахновичем Дмитрием</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Программа представляет из себя калькулятор, способный выполнять вычисления в десятичной системе счисления, переводить в троично-симметричную систему счисления и обратно.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">В троично-симметричной системе за 1 взят знак \'!\', а за -1 -- \'?\'</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Info"))
